### ISSUE TITLE
Allow adding body when creating a new release

### ISSUE THREAD

**Issue by mortenlj** [j0057/github-release#39]
When using the `release create` command, there is no option to add a body, that is only available on `release edit`. As far as I know, it is possible to add a body when creating a release through the Github API.

Would it be possible to add support for this?

**Comment by jcfr** [comment]
Hi @mortenlj , 

Thanks for the report.

A PR implementing the required changes should be pushed shortly.

In the mean time, here is a script you may be interested in: http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#publish-github-release-py

**Comment by mortenlj** [comment]
Hi. How is this PR coming along?

**Comment by jcfr** [comment]
Thanks for the reminder :+1:  

It turns out that @bstansell contributed feature and test :1st_place_medal:  See https://github.com/j0057/github-release/pull/47

New release of the package should be out shortly

**Comment by jcfr** [comment]
Closing. Feature integrated in https://github.com/j0057/github-release/commit/d47b318695ac5f7ca369adc8f3d25e452b02244a
